/*
 Navicat Premium Data Transfer

 Source Server         : postgresku
 Source Server Type    : PostgreSQL
 Source Server Version : 180004 (180004)
 Source Host           : localhost:5432
 Source Catalog        : leave_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 180004 (180004)
 File Encoding         : 65001

 Date: 20/05/2026 11:54:56
*/


-- ----------------------------
-- Table structure for employees
-- ----------------------------
DROP TABLE IF EXISTS "public"."employees";
CREATE TABLE "public"."employees" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "annual_leave_quota" int4,
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "full_name" varchar(255) COLLATE "pg_catalog"."default",
  "role" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of employees
-- ----------------------------
INSERT INTO "public"."employees" VALUES (1, 12, 'john.doe@mail.com', 'John Doe', 'EMPLOYEE');
INSERT INTO "public"."employees" VALUES (3, 10, 'michael.johnson@mail.com', 'Michael Johnson', 'EMPLOYEE');
INSERT INTO "public"."employees" VALUES (4, 8, 'sarah.williams@mail.com', 'Sarah Williams', 'EMPLOYEE');
INSERT INTO "public"."employees" VALUES (5, 12, 'david.brown@mail.com', 'David Brown', 'EMPLOYEE');
INSERT INTO "public"."employees" VALUES (6, 15, 'emily.davis@mail.com', 'Emily Davis', 'EMPLOYEE');
INSERT INTO "public"."employees" VALUES (7, 20, 'manager.one@mail.com', 'Manager One', 'MANAGER');
INSERT INTO "public"."employees" VALUES (8, 20, 'manager.two@mail.com', 'Manager Two', 'MANAGER');
INSERT INTO "public"."employees" VALUES (2, 10, 'jane.smith@mail.com', 'Jane Smith', 'EMPLOYEE');

-- ----------------------------
-- Auto increment value for employees
-- ----------------------------
SELECT setval('"public"."employees_id_seq"', 8, true);

-- ----------------------------
-- Uniques structure for table employees
-- ----------------------------
ALTER TABLE "public"."employees" ADD CONSTRAINT "ukj9xgmd0ya5jmus09o0b8pqrpb" UNIQUE ("email");

-- ----------------------------
-- Checks structure for table employees
-- ----------------------------
ALTER TABLE "public"."employees" ADD CONSTRAINT "employees_role_check" CHECK (role::text = ANY (ARRAY['EMPLOYEE'::character varying, 'MANAGER'::character varying]::text[]));

-- ----------------------------
-- Primary Key structure for table employees
-- ----------------------------
ALTER TABLE "public"."employees" ADD CONSTRAINT "employees_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Table structure for leave_requests
-- ----------------------------
DROP TABLE IF EXISTS "public"."leave_requests";
CREATE TABLE "public"."leave_requests" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "end_date" date,
  "reason" varchar(255) COLLATE "pg_catalog"."default",
  "start_date" date,
  "status" varchar(255) COLLATE "pg_catalog"."default",
  "employee_id" int8
)
;

-- ----------------------------
-- Records of leave_requests
-- ----------------------------
INSERT INTO "public"."leave_requests" VALUES (2, '2025-05-21', 'Acara keluarga', '2025-05-20', 'APPROVED', 2);
INSERT INTO "public"."leave_requests" VALUES (1, '2026-05-20', 'ada', '2026-05-19', 'REJECTED', 1);
INSERT INTO "public"."leave_requests" VALUES (3, '2025-05-23', 'Acara keluarga', '2025-05-22', 'PENDING', 2);

-- ----------------------------
-- Auto increment value for leave_requests
-- ----------------------------
SELECT setval('"public"."leave_requests_id_seq"', 3, true);

-- ----------------------------
-- Checks structure for table leave_requests
-- ----------------------------
ALTER TABLE "public"."leave_requests" ADD CONSTRAINT "leave_requests_status_check" CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying]::text[]));

-- ----------------------------
-- Primary Key structure for table leave_requests
-- ----------------------------
ALTER TABLE "public"."leave_requests" ADD CONSTRAINT "leave_requests_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table leave_requests
-- ----------------------------
ALTER TABLE "public"."leave_requests" ADD CONSTRAINT "fkrxff2xg1kffbjfh5maxwoqyhw" FOREIGN KEY ("employee_id") REFERENCES "public"."employees" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

